language: scala

services:
  - rabbitmq
install:
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo rabbitmq-plugins enable rabbitmq_federation
  - sudo rabbitmq-plugins enable rabbitmq_federation_management
  - sudo service rabbitmq-server restart
script:
  - curl -u guest:guest http://localhost:15672/api/overview
  - sbt test:run
